/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // External link
    {
      type: 'doc',
      label: 'Introduction', // The link label
      id: 'intro', // The external URL
    },
	{
		'Coding Standard':[
			{type:'doc',id:'coding-standards/reactjs', label: 'React JS'},
			{type:'doc',id:'coding-standards/react-native', label: 'React Native'},
			{type:'doc',id:'coding-standards/node-js', label: 'Node JS'},
			{type:'doc',id:'coding-standards/java', label: 'Java'},
			{type:'doc',id:'coding-standards/Nifi', label: 'Nifi'},
		]
		
	  },
  ],

};

module.exports = sidebars;
